version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 256M
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./data/static-data:/home/app/web/staticfiles
      - ./data/media-data:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - postgres

  postgres:
    image: 'postgres:14.0'
    ports:
      - '50432:5432'
    env_file:
      - ./.env.prod
    volumes:
      - ./data/db/postgres/:/var/lib/postgresql/data/

  nginx:
    build: ./nginx
    ports:
      - 443:443
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    volumes:
      - ./data/static-data:/home/app/web/staticfiles
      - ./data/media-data:/home/app/web/mediafiles
    depends_on:
      - web
