version: '1.0'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passoward
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
